import type { BrainFile, BrainProject, PromptTemplate } from '../types/brain'

export const fixtureFiles: BrainFile[] = [
  {
    id: 'project',
    path: 'brain/projects/shadowspire/PROJECT.md',
    name: 'PROJECT.md',
    title: 'ShadowSpire',
    kind: 'project',
    projectId: 'shadowspire',
    category: 'PROJECT',
    updatedAt: '2026-07-01T00:00:00.000Z',
    content: '# ShadowSpire\n\n## Summary\nA Phaser wizard platformer.\n\n## Tags\nphaser, platformer',
  },
  {
    id: 'architecture',
    path: 'brain/projects/shadowspire/ARCHITECTURE.md',
    name: 'ARCHITECTURE.md',
    title: 'Architecture',
    kind: 'project',
    projectId: 'shadowspire',
    category: 'ARCHITECTURE',
    updatedAt: '2026-07-01T00:00:00.000Z',
    content: '# Architecture\n\nPhaser owns simulation. React owns overlays.',
  },
  {
    id: 'standards',
    path: 'brain/global/CODING_STANDARDS.md',
    name: 'CODING_STANDARDS.md',
    title: 'Coding Standards',
    kind: 'global',
    category: 'CODING_STANDARDS',
    updatedAt: '2026-07-01T00:00:00.000Z',
    content: '# Coding Standards\n\nKeep changes scoped and typed.',
  },
  {
    id: 'todo',
    path: 'brain/projects/shadowspire/TODO.md',
    name: 'TODO.md',
    title: 'Todo',
    kind: 'project',
    projectId: 'shadowspire',
    category: 'TODO',
    updatedAt: '2026-07-01T00:00:00.000Z',
    content: '# Todo\n\n## Known Issues\n- Jump state can stick after restart.',
  },
  {
    id: 'decisions',
    path: 'brain/projects/shadowspire/DECISIONS.md',
    name: 'DECISIONS.md',
    title: 'Decisions',
    kind: 'project',
    projectId: 'shadowspire',
    category: 'DECISIONS',
    updatedAt: '2026-07-01T00:00:00.000Z',
    content: '# Decisions\n\n| Date | Decision | Reason | Impact | Related Files | Status |\n| --- | --- | --- | --- | --- | --- |\n| 2026-07-01 | Use Phaser | Proven 2D engine | Stable loop | src/game | active |',
  },
  {
    id: 'lessons',
    path: 'brain/projects/shadowspire/LESSONS.md',
    name: 'LESSONS.md',
    title: 'Lessons',
    kind: 'project',
    projectId: 'shadowspire',
    category: 'LESSONS',
    updatedAt: '2026-07-01T00:00:00.000Z',
    content: '# Lessons\n\n- Keep visual QA routes for gameplay states.',
  },
  {
    id: 'preset-guidance',
    path: 'brain/global/CONTEXT_PRESETS.md',
    name: 'CONTEXT_PRESETS.md',
    title: 'Context Presets',
    kind: 'global',
    category: 'CONTEXT_PRESETS',
    updatedAt: '2026-07-01T00:00:00.000Z',
    content: '# Context Presets\n\n- Run lint/test/typecheck/build.\n- Preserve existing behavior.',
  },
]

export const fixtureProjects: BrainProject[] = [
  {
    id: 'shadowspire',
    name: 'ShadowSpire',
    path: 'brain/projects/shadowspire',
    summary: 'A Phaser wizard platformer.',
    status: 'Prototype',
    techStack: ['Vite', 'TypeScript', 'Phaser'],
    tags: ['phaser', 'platformer'],
    files: fixtureFiles.filter((file) => file.projectId === 'shadowspire'),
    updatedAt: '2026-07-01T00:00:00.000Z',
  },
]

export const fixturePrompts: PromptTemplate[] = [
  {
    id: 'phase',
    title: 'Phase Implementation',
    body: 'Implement this phase only and verify it.',
    sourceFileId: 'prompts',
  },
]
